apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deployment-tekton-trigger
  namespace: apiserversource-example
  labels:
    eventing.knative.dev/broker: vmevents
spec:
  broker: vmevents
  filter: {}
  filters:  #Filter using CE SQL for Events specific to Virtual Machines
    - cesql: subject LIKE '%virtualmachine%'
  subscriber:
    ref:      #Tekton Event Listener
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: python-function
      namespace: apiserversource-example